name: embedded-check

on:
  push:
jobs:

  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: insper-embarcados/actions-embedded-check@v1
        with:
          c_file: main/main.c
